-- liquibase formatted sql

--changeset roman_gurinovich:1
create table if not exists reviews
(
    id       bigserial primary key,
    value    varchar(255),
    video_id varchar(255)
);

--changeset roman_gurinovich:2
create table if not exists users
(
    chat_id   bigint      primary key ,
    name      varchar(50) not null,
    username  varchar(50),
    bot_state int         not null default 0,
    constraint unique_name_chat_id unique (chat_id, name)
);

--changeset roman_gurinovich:3
truncate reviews;
alter table reviews add column type int;

--changeset roman_gurinovich:4
alter table users add column review_num int;

--changeset roman_gurinovich:5
create table if not exists car_brands
(
    id bigserial primary key,
    brand_name varchar(30) not null
);

create table if not exists car_models
(
    id bigserial primary key,
    car_brand_id bigint not null references car_brands(id),
    model_name varchar(25)
);

create table if not exists car_model_generations
(
    id bigint generated by default as identity primary key,
    car_model_id bigint not null references car_models(id),
    start_year_of_prod date not null,
    last_year_of_prod date not null,
    generation_name varchar(25)
);

create table cars(
    id bigserial primary key,
    brand_id bigint references car_brands(id) not null,
    model_id bigint references car_models(id) not null,
    generation_id bigint references car_model_generations not null,
    vin varchar(255),
    engine_vol varchar(20),
    hp int
);

--changeset roman_gurinovich:6
alter table users add column brand_page_num int;
alter table users add column model_page_num int;

--changeset roman_gurinovich:7
alter table users add column generation_page_num int;

--changeset roman_gurinovich:8
alter table users add column car_page int;

--changeset roman_gurinovich:9
alter table cars add column mileage int;
alter table cars add column price decimal;

--changeset roman_gurinovich:10
alter table cars alter column price type int;



